0928 동적계획법
Altu-Bitu/AlgorithmStudy_LYJ pull request #10
Opened 2021-10-03 20:03 UTC by IAGREEBUT

20923번 예제는 다 맞았는데, 반례를 모르겠네요

그리고 혹시 20923번 같은 stack, queue, deque를 쓰는 문제는 디버깅을 주로 어떻게 하시나요?
vector를 사용하는 문제 같은 경우에는 단계마다 출력하면서 확인할 수 있는데,
저런 경우는 whlie(!empty())로 출력하면 내용이 전부 빠져서 다음을 진행할 수 없어 어떻게 확인해봐야할지 모르겠네요 
혹시 방법이 있을까요?

2021-10-04 04:10 UTC, HyunJiLim0406 requested changes
p2(20923 제외)
수고하셨습니다! 제가 지금 디버깅을 할 수 없어서 20923이 어떤 문제인지는 정확히 모르겠어요!
다른 코드들 전반적으로 잘 작성해주셨는데 중복이나 가독성면에서 수정할 수 있는 부분들이 있네요~
그리고 가능하면 dp 연산 하는 부분은 함수로 빼는게 좋아요
수정 후 리뷰어로 저 호출해주세요!

2021-10-04 04:10 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/20923.cpp
> +        }
여기 반복문은 최적화 할 수 있어요!
도도와 수연이가 동시에 종을 칠 수 있는 상황은 일어나지 않아요

2021-10-04 04:10 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/20923.cpp
> +int main() {
제가 지금 디버깅을 할 수 없는 상황이라 정확히 어떤 문제인지 파악하지는 못했습니다!
다만 지금 중복되는 코드가 많네요. 다 최적화할 수 있어요! 힌트를 드리자면 저희 스택 때 크레인 문제 기억나시나요?
그때 인형들의 스택을 어떤 방법으로 관리했었나요? 그리고 순서는 도도거나/도도가 아니거나로 표현할 수도 있어요

그리고 이런 스택, 큐, 덱을 디버깅하려면 해당 컨테이너를 출력하는 함수를 만들면 돼요
참조형이 아니라 value 형으로 인자를 넘기면 원본의 복사본을 함수에서 사용하기 때문에 원본이 손상되지 않고 원소를 출력할 수 있어요

이 문제는 주로 종을 치고 카드를 옮기는 과정에서 문제가 발생하는데 다시 한 번 문제를 잘 읽어보며 구현에 문제가 없는지 보면 좋을 것 같아요!

2021-10-04 04:10 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/3190.cpp
> +        }
이 부분 조금 복잡하지 않나요? 현재 위치를 (0, 0)이라고 하면 상하좌우는 어떻게 되나요?

2021-10-04 04:10 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/3190.cpp
> +}
여기도 함수없이 간단하게 표현할 수 있는 방법이 있어요!

2021-10-04 07:04 UTC, IAGREEBUT commented
일단 20923번 수정했습니다!

2021-10-04 07:15 UTC, HyunJiLim0406 reviewed
p2
확인했습니다! 추가 코멘트 달았으니 확인해주세요~

2021-10-04 07:15 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/20923.cpp
> +        }
이 부분도 아랫부분이랑 중복되네요~ 함수화를 어떻게 하는게 좋을까요?

2021-10-04 07:15 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/20923.cpp
> +        win();
winner를 인자로 넘기는건 어떨까요?

2021-10-09 08:02 UTC, IAGREEBUT commented
늦어서 죄송합니다! 
20923번 - 언급하신 부분 중복을 제거하는 방향으로 수정 
3190번 - 방향전환 방법 공부해서 반영 
했습니다!

2021-10-10 02:42 UTC, merged