0914 우선순위큐
Altu-Bitu/AlgorithmStudy_LYJ pull request #6
Opened 2021-09-19 15:45 UTC by IAGREEBUT

11000번 시간초과를 어떻게 해결해야할까요?ㅠ_ㅠ

2021-09-20 04:50 UTC, HyunJiLim0406 requested changes
p1
수고하셨습니다! 11000번에서 시간초과가 발생하는 이유는 코드에 적어놓았어요
다른 문제도 리팩토링할 수 있는 부분이 보이네요!
그리고 11723번과 3613번은 우선순위 큐 문제가 아닙니다!
저희가 내는 모든 과제가 해당 주차에 배운 알고리즘과 연관된건 아니예요~
다시 한 번 풀어볼까요!
수정 후 리뷰어로 저 호출해주세요~

추석 잘보내세요~!

2021-09-20 04:50 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/11000.cpp
> +        }
아주 잘 짚으셨습니다! 여기 때문에 시간초과가 발생해요!
이렇게 탐색을 하면 시간복잡도가 O(n)이겠네요? 이 부분의 시간 복잡도를 O(logn)으로 해야해요! 이 논리를 그대로 사용해서 시간복잡도를 줄일 수 있는 자료구조가 있었을텐데요?

2021-09-20 04:50 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/11286.cpp
> +            pq.push({abs(num), num});
오호 굳이 abs(num)까지 추가로 저장할 필요 있을까요?

2021-09-20 04:50 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/11723.cpp
> +set<int> s;
p1
하하 맞아요. 그리고 이 문제는 사실 저희가 원하는 풀이가 따로 있어요! 힌트 보고 다시 풀어볼까요?

2021-09-20 04:50 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/15903.cpp
> +        q.push(c);
별건 아니지만 여기가 중복되니까 반복문으로 처리할 수도 있겠네요!

2021-09-20 04:50 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/2493.cpp
> +            if (s.top().first >= num) {
이 부분은 논리를 살짝 수정하면 하나로 합칠 수도 있겠어요!

2021-09-20 04:50 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/2493.cpp
> +stack<pair<int, int>> s; // 탑의 높이, 몇번째 탑인지
사실 뭘 하나 더 사용하면 몇번째 탑인지만 저장해도 탑의 높이를 알 수 있어요! 한 번 고민해보세요~

2021-09-20 04:50 UTC, HyunJiLim0406 commented on 9월 14일 - 우선순위 큐/3613.cpp
> +    }
p1
이 문제에선 string에 대한 조회 연산만 하고 있어요! 굳이 정렬할 필요가 없습니다!!
큐에 넣는것도 삭제에서 연산이 발생하기 때문에 단순조회보다는 느리구요
그리고 지금 조건이나 함수들이 의미하는 바가 명확하지 않아보여요!

함수 딱 4개만 만들어볼까요?
isCpp : c++ 형식인지 확인하는 함수
isJava : java 형식인지 확인하는 함수
toCpp : c++ 형식으로 바꾸는 함수
toJava : java 형식으로 바꾸는 함수

2021-09-24 08:18 UTC, IAGREEBUT commented
우선순위 큐는 p1은 샘플코드 보고 정리해서 크게 안봐주셔도 괜찮을 것 같습니다!

2021-09-25 10:24 UTC, HyunJiLim0406 reviewed
p3
좋아요~ 머지해주세요!

2021-09-25 13:56 UTC, merged