0924 백트래킹
Altu-Bitu/AlgorithmStudy_LYJ pull request #9
Opened 2021-09-30 01:44 UTC by IAGREEBUT

2021-09-30 06:19 UTC, bsa0322 requested changes
p1. 전체적으로 잘 풀어주셨어요!! 15665만 조금 수정해서 저 다시 리뷰어로 호출해주세요! 수고하셨습니다~!

2021-09-30 06:19 UTC, bsa0322 commented on 9월 24일 - 백트래킹/10971.cpp
> +        return;
조건문을 빠져나오면 어차피 33줄이 실행될 테니, return은 하나만 있어도 괜찮겠네요~!

2021-09-30 06:19 UTC, bsa0322 commented on 9월 24일 - 백트래킹/10971.cpp
> +    }
바로 2차원 벡터에 사이즈를 assign 해준 후, v[i][j]로 사용해도 좋을 것 같아요!

2021-09-30 06:19 UTC, bsa0322 commented on 9월 24일 - 백트래킹/10971.cpp
> +            backtracking(i, cost, cnt + 1, first);
지금 주석 처리해주신 대로 조건문에 해당할 경우만 백트래킹 호출하는 풀이로 해도 맞아요!! 다른 부분에서 오류가 있었을 것 같아요. 
아마 지금 주석된 부분을 보니 원래로 돌리는 부분까지 조건문 내에 포함되어 안됐던 것 같아요! 이렇게 되면 조건문에 해당하지 않아서 함수를 호출하진 않았지만 위에서 방문처리하는 부분은 연산이 됐을 테니까, 이 경우 꼭 원래 상태로 돌리는 부분은 조건문 밖으로 빼야 해요!

2021-09-30 06:19 UTC, bsa0322 commented on 9월 24일 - 백트래킹/15665.cpp
> +    }
p1. 더 간단하게 고칠 수 있어요! 현재 같은 수를 M번을 사용하는 것은 결국 모든 경우를 탐색하는 완전탐색과 같아요. 그런데 이렇게 처리해주시는 이유는 입력으로 중복되는 수가 들어오기 때문이죠! 그렇다면 중복되는 수만 제거한다면, M번 이하로 등장했는지 검사하는 부분이 필요할까요?

2021-09-30 06:19 UTC, bsa0322 commented on 9월 24일 - 백트래킹/2529.cpp
> +}
👍👍👍

2021-09-30 06:19 UTC, bsa0322 commented on 9월 24일 - 백트래킹/2529.cpp
> +        }
p2. 꼭 조건을 만족하는 모든 수열을 구한 후, 최대 최소값을 구해나가지 않아도, 한 번에 최대 최소값을 구하는 방법이 있어요! 최대값과 최솟값이 항상 각각 무슨 수로 이루어질지 생각해볼까요?

2021-10-09 03:48 UTC, IAGREEBUT commented
너무 늦어서 죄송합니다! 
혹시 괜찮으시다면 질문 몇가지 드려도 될까요?
1. (15665)핵심이 입력한 수의 중복 제거, 순서대로 정렬 이라고 이해해서 이를 모두 지원하는 map을 사용했습니다. 풀이코드를 보니 2가지 모두 vector를 사용하셨던데, 혹시 이유가 있나요? map을 사용하면 메모리가 더 많이 잡아먹히게 될까요?
2. (2529) 백트래킹 함수 내 is_find 변수를 사용한 것은 if문으로 탈출 조건이 2가지가 있어서, 가지치기가 아닌 진짜 탐색 종료를 구분하기 위해서 만들어진 변수라고 이해했는데 이게 맞을까요? 

항상 자세히 피드백해주셔서 많은 도움을 받고 있습니다.
감사합니다!

2021-10-09 04:06 UTC, bsa0322 approved these changes
수정해주신 코드 확인했습니다! 다 너무 좋아요! 👍👍 질문에 대한 답변 드릴께요!

1. (15665)핵심이 입력한 수의 중복 제거, 순서대로 정렬 이라고 이해해서 이를 모두 지원하는 map을 사용했습니다. 풀이코드를 보니 2가지 모두 vector를 사용하셨던데, 혹시 이유가 있나요? map을 사용하면 메모리가 더 많이 잡아먹히게 될까요?
-> 우선 백트래킹 함수 내에서 이전 수가 뭐였는지 저장하며 푸는 풀이는 따로 중복 체크 없이 정렬만 이루어지면 되므로 vector를 사용하였습니다! 
유정님의 풀이와 비슷한 풀이에서 vector를 사용한 이유는, vector의 순회가 map이나 set보다 간단해서 입니다! map이나 set은 특정 key값을 찾아야 하는 경우에 사용해주시는 게 더 좋아요! 메모리도 그렇고, 시간 면에서 다소 차이가 날 거에요! 특히 해당 풀이는 (key, value)쌍이 필요하지 않으므로 map보다는 set이 더 괜찮습니다!!

2. (2529) 백트래킹 함수 내 is_find 변수를 사용한 것은 if문으로 탈출 조건이 2가지가 있어서, 가지치기가 아닌 진짜 탐색 종료를 구분하기 위해서 만들어진 변수라고 이해했는데 이게 맞을까요?
-> 넵! 맞습니다!! 처음 if문의 부등호 판단은 가지치기 부분이고, 두 번째 if문은 답을 찾았으므로  더 이상 탐색을 하지 않기 위한 탐색 종료 조건 맞습니다! 제가 기억은 잘 안나는 데 아마 이 부분이 없으면 시간초과가 날 수도 있어요! 아닐 수도 있고요...허허 아무튼 이걸 추가해주면 시간을 훨씬 줄일 수 있습니다!

2021-10-09 04:08 UTC, IAGREEBUT commented
늦었는데도 친절한 답변 너무 감사합니다! 😊 머지하겠습니다

2021-10-09 04:11 UTC, IAGREEBUT commented
늦었는데도 친절한 답변 너무 감사합니다! 😊 머지하겠습니다

2021-10-09 04:11 UTC, merged